name: Build & Deploy Spring App to EC2

on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    name: Build & Deploy Spring App to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml
