name: Build & Deploy Spring App to EC2

on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    name: Build & Deploy Spring App to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml
      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_USER_NAME }}/online-judge-v:latest
      - name: Login to Docket Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER_NAME }}/online-judge-v:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USER_NAME }}/online-judge-v:latest
            docker stop OJS || true
            docker rm OJS || true
            docker run -dp 8080:8080 --name OJS ${{ secrets.DOCKER_USER_NAME }}/online-judge-v:latest

